chore: bump MSRV to 1.88.0 (#192)
```
error: rustc 1.87.0 is not supported by the following packages:
  darling@0.23.0 requires rustc 1.88.0
  darling_core@0.23.0 requires rustc 1.88.0
  darling_macro@0.23.0 requires rustc 1.88.0
  instability@0.3.11 requires rustc 1.88
  instability@0.3.11 requires rustc 1.88
  instability@0.3.11 requires rustc 1.88
  time@0.3.46 requires rustc 1.88.0
  time-core@0.1.8 requires rustc 1.88.0
```